//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> branch { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual User User { get; set; }
    }
}
